#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys             #sysモジュールを読み込み

print(sys.argv)        #sysの「下の」argvに引数が入るのでprintしてみる
