#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys
 
minus, zero, plus = 0, 0, 0 #こんなふうにまとめることが可能

for n in sys.argv[1:]:     
    x = float(n)
    if x < 0.0:
        minus += 1
    elif x > 0.0:
        plus += 1
    else:
        zero += 1

print("負:", minus)
print("０:", zero)
print("正:", plus)
