#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

fruits = ["a", "b", "c", "d", "e" ]
print("0番目から2番目の要素: ", fruits[0:3])
print("0番目から2番目の要素: ", fruits[0:8])
print("2番目以降の要素: ", fruits[2:])
print("ひとつ飛ばしでリストを作成: ", fruits[0::2])
