#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

print( float(sys.argv[1]) + float(sys.argv[2]) )

