#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

#x = 1.0    #xを定義して初期化
x = float(sys.argv[1])
for n in sys.argv[2:]:     #スライスを使う
    x *= float(n)          #+=で足し込む

print(x)
