#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuichiro Hatanaka <s19c1092el@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

for line in sys.stdin:
    word = sys.stdin
    #aword = line.strip() #最後の改行を消去する
    print(word + " を標準入力から呼んだよ" )
